import type { GroupStanding, KnockoutRound, MatchItem } from "@/lib/types";

export const initialMatches: MatchItem[] = [
  {
    id: "2026-05-02-1700-t1-chn-w-rom",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国女团",
    teamB: "罗马尼亚",
    scoreA: 0,
    scoreB: 0,
    detail: "中国队第一阶段首战",
    time: "5月2日 17:00",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-02-1930-t1-chn-m-eng",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国男团",
    teamB: "英格兰",
    scoreA: 0,
    scoreB: 0,
    detail: "中国男团首场亮相",
    time: "5月2日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-0000-t4-chn-w-tpe",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国女团",
    teamB: "中国台北",
    scoreA: 0,
    scoreB: 0,
    detail: "中国女团第二场",
    time: "5月3日 0:00",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-0230-t4-chn-m-kor",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国男团",
    teamB: "韩国",
    scoreA: 0,
    scoreB: 0,
    detail: "焦点硬仗",
    time: "5月3日 2:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-1930-t1-chn-m-swe",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国男团",
    teamB: "瑞典",
    scoreA: 0,
    scoreB: 0,
    detail: "中国男团第三场",
    time: "5月3日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-1930-t4-chn-w-kor",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国女团",
    teamB: "韩国",
    scoreA: 0,
    scoreB: 0,
    detail: "中国女团焦点战",
    time: "5月3日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "m1",
    phase: "group",
    group: "A 组",
    stage: "小组赛",
    status: "live",
    table: "Table 1",
    teamA: "中国",
    teamB: "日本",
    scoreA: 2,
    scoreB: 1,
    detail: "第 4 盘进行中",
    time: "进行中",
    note: "关键场，实时比分位",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "m2",
    phase: "group",
    group: "B 组",
    stage: "小组赛",
    status: "upcoming",
    table: "Table 2",
    teamA: "韩国",
    teamB: "德国",
    scoreA: 0,
    scoreB: 0,
    detail: "预计 18:30 开始",
    time: "18:30",
    note: "待开赛",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "m3",
    phase: "knockout",
    bracketRound: "1/8 决赛",
    bracketColumn: "1/8 决赛",
    stage: "1/8 决赛",
    status: "finished",
    table: "Table 1",
    teamA: "法国",
    teamB: "中国台北",
    scoreA: 3,
    scoreB: 2,
    detail: "已结束",
    time: "16:10",
    note: "五盘大战",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "m4",
    phase: "group",
    group: "A 组",
    stage: "小组赛",
    status: "live",
    table: "Table 3",
    teamA: "瑞典",
    teamB: "巴西",
    scoreA: 1,
    scoreB: 1,
    detail: "第 3 盘进行中",
    time: "进行中",
    note: "胶着",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  }
];

export const groupStandings: GroupStanding[] = [
  { name: "A 组", subtitle: "前二晋级淘汰赛", qualified: ["中国", "瑞典"] },
  { name: "B 组", subtitle: "前二晋级淘汰赛", qualified: ["韩国", "德国"] },
  { name: "C 组", subtitle: "前二晋级淘汰赛", qualified: ["法国", "中国台北"] },
  { name: "D 组", subtitle: "前二晋级淘汰赛", qualified: ["日本", "巴西"] }
];

export const knockoutRounds: KnockoutRound[] = [
  { title: "1/8 决赛", items: ["A1 vs D2", "B1 vs C2", "C1 vs B2", "D1 vs A2"] },
  { title: "1/4 决赛", items: ["胜者 1 vs 胜者 2", "胜者 3 vs 胜者 4"] },
  { title: "半决赛 / 决赛", items: ["两场 1/4 决赛胜者进入半决赛", "半决赛胜者争冠"] }
];
