import type { MatchItem } from "@/lib/types";

export const initialMatches: MatchItem[] = [
  {
    id: "2026-05-02-1700-t1-chn-w-rom",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国女团",
    teamB: "罗马尼亚",
    scoreA: 0,
    scoreB: 0,
    detail: "中国队第一阶段首战",
    time: "5月2日 17:00",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-02-1930-t1-chn-m-eng",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国男团",
    teamB: "英格兰",
    scoreA: 0,
    scoreB: 0,
    detail: "中国男团首场亮相",
    time: "5月2日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-0000-t4-chn-w-tpe",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国女团",
    teamB: "中国台北",
    scoreA: 0,
    scoreB: 0,
    detail: "中国女团第二场",
    time: "5月3日 0:00",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-0230-t4-chn-m-kor",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国男团",
    teamB: "韩国",
    scoreA: 0,
    scoreB: 0,
    detail: "焦点硬仗",
    time: "5月3日 2:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-1930-t1-chn-m-swe",
    phase: "group",
    group: "男团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T1",
    teamA: "中国男团",
    teamB: "瑞典",
    scoreA: 0,
    scoreB: 0,
    detail: "中国男团第三场",
    time: "5月3日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  },
  {
    id: "2026-05-03-1930-t4-chn-w-kor",
    phase: "group",
    group: "女团Group 1",
    stage: "小组赛",
    status: "upcoming",
    table: "T4",
    teamA: "中国女团",
    teamB: "韩国",
    scoreA: 0,
    scoreB: 0,
    detail: "中国女团焦点战",
    time: "5月3日 19:30",
    note: "中国队重点场次",
    blessings: { incense: 0, mokugyo: 0, beads: 0 },
    togetherNow: 0,
    fortune: 0,
    sourceName: "草莓牛奶特别甜",
    sourceUrl: "",
    updatedAt: "2026-05-01T00:00:00Z",
    messages: [],
    userSession: { blessings: 0, lastMessage: "", snapshotScore: "", repaid: false }
  }
];
